version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\simdjson
platform: x64
image:
  - Visual Studio 2019
  - Visual Studio 2017
configuration: Release
environment:
  matrix:
    - SIMDJSON_BUILD_STATIC: ON
      SIMDJSON_ENABLE_THREADS: OFF
      SIMDJSON_PLATFORM: x64
    - SIMDJSON_BUILD_STATIC: ON
      SIMDJSON_ENABLE_THREADS: OFF
      SIMDJSON_PLATFORM: Win32
    - SIMDJSON_BUILD_STATIC: OFF
      SIMDJSON_ENABLE_THREADS: ON
      SIMDJSON_PLATFORM: x64

build_script:
  - set
  - mkdir build
  - cd build
  - cmake -DSIMDJSON_BUILD_STATIC=%SIMDJSON_BUILD_STATIC% -DSIMDJSON_ENABLE_THREADS=%SIMDJSON_ENABLE_THREADS% -DCMAKE_BUILD_TYPE=%Configuration% -DCMAKE_GENERATOR_PLATFORM=%SIMDJSON_PLATFORM% ..
  - cmake -LH ..
  - cmake --build . --config %Configuration% --verbose

test_script:
  - ctest --output-on-failure -C %Configuration% --verbose
  
matrix:
  fast_finish: true
  exclude:
    # Don't build all variants on 2017, just running it to make sure readme_tests succeed
    - image: Visual Studio 2017
      SIMDJSON_BUILD_STATIC: ON
      SIMDJSON_ENABLE_THREADS: OFF
